In [53]:
import numpy as np 


In [54]:
n=np.array([1,2,3,4,5,6,7,8,9,10])
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
type(n)

numpy.ndarray

In [56]:
n.shape


(10,)

In [57]:
n.size

10

In [58]:
n[2]

np.int32(3)

In [59]:
n[2:7]

array([3, 4, 5, 6, 7])

In [60]:
n[-3]

np.int32(8)

In [61]:
n[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
type(a)

numpy.ndarray

In [64]:
a.shape

(3, 3)

In [65]:
a.size

9

In [66]:
a[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [67]:
a[0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [68]:
a[1:3,2:]

array([[6],
       [9]])

In [69]:
s=np.array([[100,200,300],[400,500,600],[800,900,1000],[50,50,50]])
print(s)

[[ 100  200  300]
 [ 400  500  600]
 [ 800  900 1000]
 [  50   50   50]]


In [71]:
s[0,2]

np.int32(300)

In [72]:
s[1:2,0:2]

array([[400, 500]])

In [73]:
s[1:3,1:2]

array([[500],
       [900]])

In [77]:
s[2:,1:3]

array([[ 900, 1000],
       [  50,   50]])

In [86]:
b=np.arange(1,8,2)
print(b)

[1 3 5 7]


In [90]:
c=np.linspace(0,10,5)
print(c)

[ 0.   2.5  5.   7.5 10. ]


In [92]:
c=s.flatten()

In [93]:
print(c)

[ 100  200  300  400  500  600  800  900 1000   50   50   50]


In [94]:
c.size

12

In [95]:
c.shape

(12,)

In [97]:
np.reshape(s,(3,4))

array([[ 100,  200,  300,  400],
       [ 500,  600,  800,  900],
       [1000,   50,   50,   50]])

In [98]:
np.resize(c,5)

array([100, 200, 300, 400, 500])

In [99]:
np.resize(c,14)

array([ 100,  200,  300,  400,  500,  600,  800,  900, 1000,   50,   50,
         50,  100,  200])

In [110]:
np.random.random([3,4])


array([[0.80588665, 0.37833276, 0.79697889, 0.39901668],
       [0.26047547, 0.34026131, 0.5759259 , 0.78900481],
       [0.53962312, 0.44078672, 0.16983856, 0.64505737]])

In [109]:
np.random.uniform(1,5,5)

array([4.88047651, 2.90918948, 2.03105112, 3.40609975, 2.85510395])

In [111]:
np.random.randint(2,5,6)

array([2, 3, 2, 3, 3, 3])

In [112]:
np.random.choice(c)

np.int32(500)

In [118]:
np.random.shuffle(c)

In [119]:
print(c)

[ 500   50   50  600  800  200 1000  400  100  900   50  300]


In [124]:

e=np.random.seed(4)
print(e)

None


In [125]:
print(c)

[ 500   50   50  600  800  200 1000  400  100  900   50  300]
